# Generated by Django 3.2.1 on 2021-05-04 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAnotherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votingpower', models.BooleanField()),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myusermodel')),
            ],
        ),
    ]
